In [37]:
# importing the required libraries

import pandas as pd # for handling data in the form of tables
import numpy as np # For handling matrix
import matplotlib.pyplot as plt # for plotting

from sklearn.model_selection import train_test_split # For spliting the data into train and test
from sklearn.linear_model import LinearRegression # for using the model
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,classification_report

In [3]:
pwd

'C:\\Users\\hi\\Documents\\Artificial Intelligence'

In [10]:
# Upload the data
wine = pd.read_csv(r"C:\Users\hi\Downloads\winequalityN.csv")
wine.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [11]:
wine.isna().any()

type                    False
fixed acidity            True
volatile acidity         True
citric acid              True
residual sugar           True
chlorides                True
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                       True
sulphates                True
alcohol                 False
quality                 False
dtype: bool

In [12]:
wine = wine.fillna(method='pad')

In [13]:
wine.isna().any()

type                    False
fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [14]:
wine.isna().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [15]:
wine.count()

type                    6497
fixed acidity           6497
volatile acidity        6497
citric acid             6497
residual sugar          6497
chlorides               6497
free sulfur dioxide     6497
total sulfur dioxide    6497
density                 6497
pH                      6497
sulphates               6497
alcohol                 6497
quality                 6497
dtype: int64

In [16]:
wine.shape

(6497, 13)

In [17]:
wine.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [18]:
# <---------->

In [22]:
# Select the independendent variables(features)(lies on x-axis)
X = wine[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates','alcohol']].values

# Select the depended variables(labels)(lies on y-axis)
Y = wine['quality'].values

In [23]:
# Check the shape of x
X.shape

(6497, 11)

In [24]:
# Check the shape of y
Y.shape

(6497,)

In [25]:
# divide the data into train and test
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [26]:
x_train.shape
x_test.shape

(1300, 11)

In [27]:
y_train.shape
y_test.shape

(1300,)

In [29]:
# build the model using training data
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [30]:
# the intercept
model.intercept_

50.237927032478325

In [31]:
# the slope
model.coef_

array([ 7.23355040e-02, -1.31291061e+00, -1.75901371e-01,  4.37557920e-02,
       -6.30759831e-01,  6.56384554e-03, -2.71615155e-03, -4.92657286e+01,
        3.71213449e-01,  7.57203006e-01,  2.75015544e-01])

In [33]:
# Apply the model on test set
y_pred = model.predict(x_test)
y_pred

array([5.90526255, 5.30039125, 6.073549  , ..., 6.26477744, 5.66552084,
       6.35963968])

In [34]:
y_pred.shape

(1300,)

In [35]:
# Now, let's make a dataframe with actual values and predicted values.
# flatten() function is used to get a copy of an given array collapsed into one dimension.
Actual_predicted=pd.DataFrame({"Actual": y_test.flatten(), "Predicted": y_pred.flatten()})
Actual_predicted.head()

Actual  Predicted
0       6   5.905263
1       6   5.300391
2       5   6.073549
3       6   4.772151
4       5   5.425160

In [39]:
r2_score(y_test,y_pred)

0.299549447684735

In [41]:
mean_absolute_error(y_test,y_pred)

0.5660002026068848

In [42]:
mean_squared_error(y_test,y_pred)

0.5337429063964494

In [43]:
# <----------->

In [44]:
# predicting the unknown using model

In [45]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11])

In [46]:
y = model.predict(x.reshape(1,-1))
y

array([-335.98937542])