<a href="https://colab.research.google.com/github/9515391831/AI-Supervised/blob/main/Ridge_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ridge Regression And Classification:

*Ridge regression also known as Tikhonov regularization.*

*Ridge regression is one of the regularization techniques.*

*The Ridge regression is a technique which is specialized to analyze multiple regression data which is multicollinearity in nature.*

There are two types of regularization:

1.L1 Regularization or Lasso Regularization.

2.L2 Regularization or Ridge Regularization.

*Ridge regression prevents overfitting*

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
a=pd.read_csv("students_placement_data.csv")
a.head()

Roll No Gender  ... registered_for_ Placement_Training  placement status
0        1      M  ...                                 NO        Not placed
1        2      F  ...                                yes            Placed
2        3      F  ...                                yes        Not placed
3        4      M  ...                                yes        Not placed
4        5      M  ...                                yes        Not placed

[5 rows x 9 columns]

In [ ]:
a.isna().any()

Roll No                               False
Gender                                False
Section                               False
SSC Percentage                        False
inter_Diploma_percentage              False
B.Tech_percentage                     False
Backlogs                              False
registered_for_ Placement_Training    False
placement status                      False
dtype: bool

In [ ]:
a.shape

(117, 9)

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=a['B.Tech_percentage'].values.reshape(-1,1)
y=a['Backlogs'].values.reshape(-1,1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# Ridgeregression

In [ ]:
ri=Ridge(alpha=1.0)
ri

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
ri.fit(x,y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
z=ri.predict(x_test)
z

array([[ 2.91494367],
       [ 9.69144275],
       [-0.17838183],
       [-1.09242124],
       [ 4.98616598],
       [ 4.08563454],
       [-1.02037873],
       [ 9.03855746],
       [ 4.09463985],
       [ 4.44584711],
       [15.34227754],
       [10.08317393],
       [ 8.89897508],
       [18.40408443],
       [ 0.2808892 ],
       [ 2.25755571],
       [-4.06417499],
       [ 0.89325058],
       [ 1.51911993],
       [ 5.11224038],
       [14.4417461 ],
       [ 1.11388079],
       [ 9.48882318],
       [ 6.44952957]])

In [ ]:
ri.coef_

array([[-0.45026572]])

In [ ]:
ri.intercept_

array([32.45237489])

<h2>In these regression accuracy scores are find in this way:</h2>




In [ ]:
ri.score(x,y)

0.7353267162115953

In [ ]:
ri.score(y_test,z)

-21.38950188799552

In [ ]:
ri.score(x_train,y_train)

0.721019991199183

In [ ]:
ri.score(x_test,y_test)

0.758725120096216

# RidgeregressionCV(cv=cross validation)

In [ ]:
from sklearn.linear_model import RidgeCV

In [ ]:
rcv=RidgeCV()
rcv

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=None, fit_intercept=True,
        gcv_mode=None, normalize=False, scoring=None, store_cv_values=False)

In [ ]:
rcv.fit(x,y)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=None, fit_intercept=True,
        gcv_mode=None, normalize=False, scoring=None, store_cv_values=False)

In [ ]:
rcv.coef_

array([[-0.45002584]])

In [ ]:
rcv.intercept_

array([32.43727611])

In [ ]:
m=rcv.predict(x_test)
m

array([[ 2.91558092],
       [ 9.68846983],
       [-0.17609661],
       [-1.08964906],
       [ 4.98569979],
       [ 4.08564811],
       [-1.01764493],
       [ 9.03593236],
       [ 4.09464863],
       [ 4.44566878],
       [15.33629414],
       [10.07999232],
       [ 8.89642435],
       [18.39646986],
       [ 0.28292975],
       [ 2.25854319],
       [-4.05981962],
       [ 0.8949649 ],
       [ 1.52050082],
       [ 5.11170703],
       [14.43624246],
       [ 1.11547756],
       [ 9.48595821],
       [ 6.44828378]])

In [ ]:
rcv.score(x,y)

0.7353264611346189

In [ ]:
rcv.score(x_train,y_train)

0.7210756989181601

# Ridgeclassification

In [ ]:
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
e=a['Backlogs'].values.reshape(-1,1)
f=a['placement status'].values.reshape(-1,1)

In [ ]:
e_train,e_test,f_train,f_test=train_test_split(e,f,test_size=0.2)

In [ ]:
rc=RidgeClassifier()
rc.fit(e,f)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_ridge.py:940: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=None,
                solver='auto', tol=0.001)

In [ ]:
rc.coef_

array([[-0.06585698]])

In [ ]:
rc.intercept_

array([-0.06258799])

In [ ]:
pre=rc.predict(e_test)
pre

array(['Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed'],
      dtype='<U10')

In [ ]:
rc.score(e,f)

0.6666666666666666

In [ ]:
rc.score(e_train,f_train)

0.6559139784946236

In [ ]:
rc.score(e_test,f_test)

0.7083333333333334

#RidgeclassificationCV

In [ ]:
from sklearn.linear_model import RidgeClassifierCV

In [ ]:
rccv=RidgeClassifierCV().fit(e,f)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_ridge.py:1853: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
rccv.coef_

array([[-0.06572994]])

In [ ]:
rccv.intercept_

array([-0.06311026])

In [ ]:
rccv.predict(e_test)

array(['Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed',
       'Not placed', 'Not placed', 'Not placed', 'Not placed'],
      dtype='<U10')

In [ ]:
rccv.score(e,f)

0.6666666666666666

In [ ]:
rccv.score(e_test,f_test)

0.7083333333333334

In [ ]:
rccv.score(e_train,f_train)

0.6559139784946236