In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,roc_auc_score,mean_absolute_error,confusion_matrix,classification_report,precision_score,average_precision_score

In [2]:
#reading the given data
a = pd.read_csv(r"C:\Users\hi\Downloads\Iris.csv")
a.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
#printing the no.of rows and columns in the data
a.shape

(150, 6)

In [4]:
#printing the columns in the data
a.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [5]:
#taking the independent and dependent variables
x=a[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=a['Species']

In [6]:
#splitting the data into training and testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
# <------------->

In [15]:
# Preparing the model using linear kernel

In [7]:
#preparing the model based on the training data
model=SVC(kernel='linear')
model.fit(x_train,y_train)

SVC(kernel='linear')

In [8]:
#predicting the test values
predicted=model.predict(x_test)
predicted

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [9]:
#printing the actual and predicted values
actual_predicted=pd.DataFrame({'actual':y_test,'predicted':predicted})
actual_predicted

actual        predicted
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

In [10]:
#printing the accuracy of the model
accuracy=accuracy_score(y_test,predicted)*100
accuracy

100.0

In [11]:
#printing the precision of the model
precision=precision_score(y_test,predicted,average=None)*100
precision

array([100., 100., 100.])

In [12]:
#printing the confusion matrix
confusion_matrix(y_test,predicted)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [13]:
#printing the classification report
classification_report(y_test,predicted)

'                 precision    recall  f1-score   support\n\n    Iris-setosa       1.00      1.00      1.00        10\nIris-versicolor       1.00      1.00      1.00         9\n Iris-virginica       1.00      1.00      1.00        11\n\n       accuracy                           1.00        30\n      macro avg       1.00      1.00      1.00        30\n   weighted avg       1.00      1.00      1.00        30\n'

In [29]:
# Predicting the unkonwn using model

m = np.array([[1.1,2.2,3.3,4.4]])
n = model.predict(m.reshape(1,-1))
n

array(['Iris-virginica'], dtype=object)

In [18]:
# <------------>

In [19]:
# <------------->

In [20]:
# Preparing the model using rdf kernel

In [21]:
#preparing the model based on the training data
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

SVC()

In [22]:
#predicting the values
y_predicted=model.predict(x_test)
y_predicted

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [23]:
#printing the actual and predicted values
actual_predicted=pd.DataFrame({'actual':y_test,'predicted':y_predicted})
actual_predicted

actual        predicted
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

In [24]:
#printing the accuracy of the model
accuracy=accuracy_score(y_test,y_predicted)*100
accuracy

100.0

In [25]:
#printing the precision of the model
precision=precision_score(y_test,y_predicted,average=None)*100
precision

array([100., 100., 100.])

In [26]:
#printing the confusion matrix 
confusion_matrix(y_test,predicted)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [27]:
#printing the classification report
classification_report(y_test,predicted)

'                 precision    recall  f1-score   support\n\n    Iris-setosa       1.00      1.00      1.00        10\nIris-versicolor       1.00      1.00      1.00         9\n Iris-virginica       1.00      1.00      1.00        11\n\n       accuracy                           1.00        30\n      macro avg       1.00      1.00      1.00        30\n   weighted avg       1.00      1.00      1.00        30\n'

In [31]:
# Predicting the unkonwn using model

m = np.array([[1.1,2.2,3.3,4.3]])
n = model.predict(m.reshape(1,-1))
n

array(['Iris-virginica'], dtype=object)

In [28]:
# <------------->